In [2]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("student-mat.csv", sep=";")
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data("student-mat.csv")

In [4]:
x_train = x_train / 255.0
x_test = x_test / 255.0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    str
 1   sex         395 non-null    str
 2   age         395 non-null    int64
 3   address     395 non-null    str
 4   famsize     395 non-null    str
 5   Pstatus     395 non-null    str
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    str
 9   Fjob        395 non-null    str
 10  reason      395 non-null    str
 11  guardian    395 non-null    str
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    str
 16  famsup      395 non-null    str
 17  paid        395 non-null    str
 18  activities  395 non-null    str
 19  nursery     395 non-null    str
 20  higher      395 non-null    str
 21  internet    395 non-null    str
 22  romantic    395 non-null    str
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), str(17)
memory usage: 102.0 KB

In [6]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le=LabelEncoder()

In [9]:
catergorical=df.select_dtypes(include='object').columns
print(catergorical)

Index(['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob',
       'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic'],
      dtype='str')

C:\Users\user\AppData\Local\Temp\ipykernel_24548\1027182621.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  catergorical=df.select_dtypes(include='object').columns

In [23]:
for i in catergorical:
  df[i]=le.fit_transform(df[i])

In [11]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,0,0,18,1,0,0,4,4,0,4,...,4,3,4,1,1,3,6,5,6,6
1,0,0,17,1,0,1,1,1,0,2,...,5,3,3,1,1,3,4,5,5,6
2,0,0,15,1,1,1,1,1,0,2,...,4,3,2,2,3,3,10,7,8,10
3,0,0,15,1,0,1,4,2,1,3,...,3,2,2,1,1,5,2,15,14,15
4,0,0,16,1,0,1,3,3,2,2,...,4,3,2,1,2,5,4,6,10,10

In [12]:
x=df.drop('G3',axis=1)
y=df['G3']

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [17]:
model = Sequential([
    tf.keras.Input(shape=(32,)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)
])

In [18]:
model.compile(optimizer='adam',loss='mse',metrics=['r2_score'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [19]:
model.fit(x_train,y_train,epochs=100,batch_size=32,validation_data=(x_test,y_test))

Epoch 1/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 3s 57ms/step - loss: 122.2413 - r2_score: -5.3483 - val_loss: 109.4247 - val_r2_score: -2.9663
Epoch 2/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 93.3997 - r2_score: -3.8505 - val_loss: 77.0579 - val_r2_score: -1.7931
Epoch 3/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 55.5431 - r2_score: -1.8845 - val_loss: 39.3427 - val_r2_score: -0.4260
Epoch 4/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 22.0557 - r2_score: -0.1454 - val_loss: 21.5410 - val_r2_score: 0.2192
Epoch 5/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 12.4567 - r2_score: 0.3531 - val_loss: 19.5144 - val_r2_score: 0.2927
Epoch 6/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 8.9807 - r2_score: 0.5336 - val_loss: 13.5518 - val_r2_score: 0.5088
Epoch 7/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 6.7859 - r2_score: 0.6476 - val_loss: 11.6026 - val_r2_score: 0.5794
Epoch 8/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 5.9991 - r2_score: 0.6884 - val_loss: 11.1911 - val_r2_score: 0.5944
Epoch 9/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 5.3697 - r2_score: 0.7211 - val_loss: 11.1511 - val_r2_score: 0.5958
Epoch 10/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 4.9593 - r2_score: 0.7425 - val_loss: 10.3172 - val_r2_score: 0.6260
Epoch 11/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 4.5045 - r2_score: 0.7661 - val_loss: 10.3413 - val_r2_score: 0.6252
Epoch 12/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 4.1851 - r2_score: 0.7827 - val_loss: 10.4155 - val_r2_score: 0.6225
Epoch 13/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3.9015 - r2_score: 0.7974 - val_loss: 10.0652 - val_r2_score: 0.6352
Epoch 14/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 3.6247 - r2_score: 0.8118 - val_loss: 9.8028 - val_r2_score: 0.6447
Epoch 15/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 3.3464 - r2_score: 0.8262 - val_loss: 9.8079 - val_r2_score: 0.6445
Epoch 16/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 3.1239 - r2_score: 0.8378 - val_loss: 9.5502 - val_r2_score: 0.6538
Epoch 17/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 2.8888 - r2_score: 0.8500 - val_loss: 9.6338 - val_r2_score: 0.6508
Epoch 18/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2.6766 - r2_score: 0.8610 - val_loss: 9.5704 - val_r2_score: 0.6531
Epoch 19/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 2.4830 - r2_score: 0.8711 - val_loss: 9.3367 - val_r2_score: 0.6616
Epoch 20/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 2.2908 - r2_score: 0.8810 - val_loss: 9.5860 - val_r2_score: 0.6525
Epoch 21/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 2.1117 - r2_score: 0.8903 - val_loss: 9.3511 - val_r2_score: 0.6611
Epoch 22/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.9598 - r2_score: 0.8982 - val_loss: 9.3636 - val_r2_score: 0.6606
Epoch 23/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.8065 - r2_score: 0.9062 - val_loss: 9.3465 - val_r2_score: 0.6612
Epoch 24/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 1.6600 - r2_score: 0.9138 - val_loss: 9.2184 - val_r2_score: 0.6659
Epoch 25/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.5493 - r2_score: 0.9195 - val_loss: 9.3394 - val_r2_score: 0.6615
Epoch 26/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.4365 - r2_score: 0.9254 - val_loss: 9.0638 - val_r2_score: 0.6715
Epoch 27/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.3060 - r2_score: 0.9322 - val_loss: 9.3219 - val_r2_score: 0.6621
Epoch 28/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1.2057 - r2_score: 0.9374 - val_loss: 9.0376 - val_r2_score: 0.6724
Epoch 29/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1.1016 - r2_score: 0.9428 - val_loss: 9.2671 - val_r2_score: 0.6641
Epoch 30/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.0128 - r2_score: 0.9474 - val_loss: 9.3031 - val_r2_score: 0.6628
Epoch 31/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.9430 - r2_score: 0.9510 - val_loss: 9.1208 - val_r2_score: 0.6694
Epoch 32/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8529 - r2_score: 0.9557 - val_loss: 9.2553 - val_r2_score: 0.6645
Epoch 33/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.7856 - r2_score: 0.9592 - val_loss: 9.1695 - val_r2_score: 0.6676
Epoch 34/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.7336 - r2_score: 0.9619 - val_loss: 9.3373 - val_r2_score: 0.6616
Epoch 35/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.6729 - r2_score: 0.9651 - val_loss: 9.2161 - val_r2_score: 0.6659
Epoch 36/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.6253 - r2_score: 0.9675 - val_loss: 9.3341 - val_r2_score: 0.6617
Epoch 37/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.5657 - r2_score: 0.9706 - val_loss: 9.2447 - val_r2_score: 0.6649
Epoch 38/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.5242 - r2_score: 0.9728 - val_loss: 9.3617 - val_r2_score: 0.6607
Epoch 39/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.4750 - r2_score: 0.9753 - val_loss: 9.2732 - val_r2_score: 0.6639
Epoch 40/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.4396 - r2_score: 0.9772 - val_loss: 9.2435 - val_r2_score: 0.6650
Epoch 41/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.4019 - r2_score: 0.9791 - val_loss: 9.3207 - val_r2_score: 0.6622
Epoch 42/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.3676 - r2_score: 0.9809 - val_loss: 9.2309 - val_r2_score: 0.6654
Epoch 43/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.3365 - r2_score: 0.9825 - val_loss: 9.2532 - val_r2_score: 0.6646
Epoch 44/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.3077 - r2_score: 0.9840 - val_loss: 9.3359 - val_r2_score: 0.6616
Epoch 45/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.2852 - r2_score: 0.9852 - val_loss: 9.3147 - val_r2_score: 0.6624
Epoch 46/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.2586 - r2_score: 0.9866 - val_loss: 9.2741 - val_r2_score: 0.6638
Epoch 47/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2398 - r2_score: 0.9875 - val_loss: 9.3580 - val_r2_score: 0.6608
Epoch 48/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.2211 - r2_score: 0.9885 - val_loss: 9.2256 - val_r2_score: 0.6656
Epoch 49/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.2000 - r2_score: 0.9896 - val_loss: 9.2902 - val_r2_score: 0.6633
Epoch 50/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.1832 - r2_score: 0.9905 - val_loss: 9.2870 - val_r2_score: 0.6634
Epoch 51/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1695 - r2_score: 0.9912 - val_loss: 9.2236 - val_r2_score: 0.6657
Epoch 52/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1546 - r2_score: 0.9920 - val_loss: 9.3267 - val_r2_score: 0.6619
Epoch 53/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1413 - r2_score: 0.9927 - val_loss: 9.2220 - val_r2_score: 0.6657
Epoch 54/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1325 - r2_score: 0.9931 - val_loss: 9.3703 - val_r2_score: 0.6604
Epoch 55/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1174 - r2_score: 0.9939 - val_loss: 9.2208 - val_r2_score: 0.6658
Epoch 56/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1078 - r2_score: 0.9944 - val_loss: 9.3142 - val_r2_score: 0.6624
Epoch 57/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0994 - r2_score: 0.9948 - val_loss: 9.2516 - val_r2_score: 0.6647
Epoch 58/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0934 - r2_score: 0.9951 - val_loss: 9.3191 - val_r2_score: 0.6622
Epoch 59/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0834 - r2_score: 0.9957 - val_loss: 9.3161 - val_r2_score: 0.6623
Epoch 60/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0757 - r2_score: 0.9961 - val_loss: 9.2783 - val_r2_score: 0.6637
Epoch 61/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0701 - r2_score: 0.9964 - val_loss: 9.2944 - val_r2_score: 0.6631
Epoch 62/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0644 - r2_score: 0.9967 - val_loss: 9.2833 - val_r2_score: 0.6635
Epoch 63/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0585 - r2_score: 0.9970 - val_loss: 9.2500 - val_r2_score: 0.6647
Epoch 64/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0548 - r2_score: 0.9972 - val_loss: 9.3737 - val_r2_score: 0.6602
Epoch 65/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0503 - r2_score: 0.9974 - val_loss: 9.2473 - val_r2_score: 0.6648
Epoch 66/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0460 - r2_score: 0.9976 - val_loss: 9.2372 - val_r2_score: 0.6652
Epoch 67/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0397 - r2_score: 0.9979 - val_loss: 9.3087 - val_r2_score: 0.6626
Epoch 68/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0369 - r2_score: 0.9981 - val_loss: 9.2738 - val_r2_score: 0.6639
Epoch 69/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0336 - r2_score: 0.9983 - val_loss: 9.3329 - val_r2_score: 0.6617
Epoch 70/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0309 - r2_score: 0.9984 - val_loss: 9.3114 - val_r2_score: 0.6625
Epoch 71/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0284 - r2_score: 0.9985 - val_loss: 9.2455 - val_r2_score: 0.6649
Epoch 72/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0272 - r2_score: 0.9986 - val_loss: 9.2986 - val_r2_score: 0.6630
Epoch 73/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0239 - r2_score: 0.9988 - val_loss: 9.3231 - val_r2_score: 0.6621
Epoch 74/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0230 - r2_score: 0.9988 - val_loss: 9.2306 - val_r2_score: 0.6654
Epoch 75/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0200 - r2_score: 0.9990 - val_loss: 9.3114 - val_r2_score: 0.6625
Epoch 76/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0180 - r2_score: 0.9991 - val_loss: 9.3166 - val_r2_score: 0.6623
Epoch 77/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0166 - r2_score: 0.9991 - val_loss: 9.3190 - val_r2_score: 0.6622
Epoch 78/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0151 - r2_score: 0.9992 - val_loss: 9.3192 - val_r2_score: 0.6622
Epoch 79/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0139 - r2_score: 0.9993 - val_loss: 9.2936 - val_r2_score: 0.6631
Epoch 80/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0125 - r2_score: 0.9994 - val_loss: 9.2800 - val_r2_score: 0.6636
Epoch 81/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0114 - r2_score: 0.9994 - val_loss: 9.3429 - val_r2_score: 0.6614
Epoch 82/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0106 - r2_score: 0.9994 - val_loss: 9.3191 - val_r2_score: 0.6622
Epoch 83/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0096 - r2_score: 0.9995 - val_loss: 9.3175 - val_r2_score: 0.6623
Epoch 84/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0087 - r2_score: 0.9995 - val_loss: 9.3008 - val_r2_score: 0.6629
Epoch 85/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0078 - r2_score: 0.9996 - val_loss: 9.3091 - val_r2_score: 0.6626
Epoch 86/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0072 - r2_score: 0.9996 - val_loss: 9.3240 - val_r2_score: 0.6620
Epoch 87/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0066 - r2_score: 0.9997 - val_loss: 9.3044 - val_r2_score: 0.6627
Epoch 88/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0061 - r2_score: 0.9997 - val_loss: 9.3540 - val_r2_score: 0.6610
Epoch 89/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0057 - r2_score: 0.9997 - val_loss: 9.3470 - val_r2_score: 0.6612
Epoch 90/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0052 - r2_score: 0.9997 - val_loss: 9.3330 - val_r2_score: 0.6617
Epoch 91/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0047 - r2_score: 0.9998 - val_loss: 9.3250 - val_r2_score: 0.6620
Epoch 92/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0042 - r2_score: 0.9998 - val_loss: 9.3448 - val_r2_score: 0.6613
Epoch 93/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0039 - r2_score: 0.9998 - val_loss: 9.3362 - val_r2_score: 0.6616
Epoch 94/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0037 - r2_score: 0.9998 - val_loss: 9.3312 - val_r2_score: 0.6618
Epoch 95/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0033 - r2_score: 0.9998 - val_loss: 9.3531 - val_r2_score: 0.6610
Epoch 96/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0031 - r2_score: 0.9998 - val_loss: 9.3477 - val_r2_score: 0.6612
Epoch 97/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0028 - r2_score: 0.9999 - val_loss: 9.3475 - val_r2_score: 0.6612
Epoch 98/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0025 - r2_score: 0.9999 - val_loss: 9.3474 - val_r2_score: 0.6612
Epoch 99/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0024 - r2_score: 0.9999 - val_loss: 9.3414 - val_r2_score: 0.6614
Epoch 100/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0022 - r2_score: 0.9999 - val_loss: 9.3434 - val_r2_score: 0.6613

In [20]:
predict=model.predict(x_test)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step

In [21]:
from sklearn.metrics import r2_score

In [22]:
print(r2_score(y_test,predict))

0.6613336205482483